package project.euler;
/**
 * Projectdescription:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * @author bayerlma
 *
 */
public class EvenFibonacciNumbers {

  public int calculate(final int limit){
    int sum = 0;
    int previousNumber = 0;
    int currentNumber = 1;
    int helper = 0;
    while(currentNumber <= limit){
      helper = currentNumber;
      currentNumber = currentNumber + previousNumber;
      previousNumber =  helper;
      System.out.println ("number: " + currentNumber);
      if(currentNumber%2 == 0){
        sum += currentNumber;
      }
    }

    return sum;
  }

  public static void main(final String[] args) {
    final EvenFibonacciNumbers instance = new EvenFibonacciNumbers();
    System.out.println (instance.calculate(4000000));
  }

}
